package A51388.spinnet.data.remote

import A51388.spinnet.BuildConfig
import A51388.spinnet.data.model.GeneratedRoutine
import A51388.spinnet.data.model.GeneratedShot
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GroqApiService {

    private val API_KEY = BuildConfig.GROQ_API_KEY
    private const val BASE_URL = "https://api.groq.com/openai/v1/chat/completions"
    private const val MODEL = "llama-3.3-70b-versatile"

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .build()

    private val systemPrompt = """
        És um assistente especializado em ténis de mesa.
        Quando o utilizador pedir um plano de treino, deves devolver APENAS um objeto JSON válido com este schema exato, sem texto adicional, sem markdown, sem backticks:
        {
          "title": "string",
          "shots": [
            {
              "index": 1,
              "zone": 9,
              "spinName": "Top Spin",
              "velocity": 45,
              "freq": "High",
              "racketSide": "Forehand"
            }
          ]
        }
        
        Regras para os campos:
        - "zone": número inteiro entre 1 e 16. Zonas 1-8 são o lado do jogador, zonas 9-16 são o lado do adversário.
        - "spinName": um dos seguintes valores exatos: "Top Spin", "Back Spin", "Left Topspin", "Right Topspin", "Left Side-Spin", "Right Side-Spin", "Left Backspin", "Right Backspin"
        - "velocity": número inteiro entre 20 e 70 (metros por segundo)
        - "freq": "Low", "Med" ou "High"
        - "racketSide": "Forehand", "Backhand" ou "Both"
        - "index": começa em 1 e é sequencial
        
        Gera entre 4 e 12 shots dependendo da duração e complexidade pedida.
        Adapta as zonas, spins e racket sides ao nível e objetivo pedido pelo utilizador.
        Devolve APENAS o JSON. Sem mais nada.
    """.trimIndent()

    suspend fun generateRoutine(userPrompt: String): Result<GeneratedRoutine> =
        withContext(Dispatchers.IO) {
            try {
                val messages = JSONArray().apply {
                    put(JSONObject().put("role", "system").put("content", systemPrompt))
                    put(JSONObject().put("role", "user").put("content", userPrompt))
                }
                val body = JSONObject()
                    .put("model", MODEL)
                    .put("messages", messages)
                    .put("temperature", 0.7)
                    .put("max_tokens", 2048)
                    .toString()
                    .toRequestBody("application/json".toMediaType())

                val request = Request.Builder()
                    .url(BASE_URL)
                    .addHeader("Authorization", "Bearer $API_KEY")
                    .addHeader("Content-Type", "application/json")
                    .post(body)
                    .build()

                val response = client.newCall(request).execute()
                val responseBody = response.body?.string() ?: return@withContext Result.failure(Exception("Resposta vazia"))

                if (!response.isSuccessful) {
                    val errMsg = try {
                        JSONObject(responseBody).getJSONObject("error").getString("message")
                    } catch (e: Exception) {
                        "HTTP ${response.code}: $responseBody"
                    }
                    return@withContext Result.failure(Exception("Erro na API Groq: $errMsg"))
                }

                val jsonResponse = JSONObject(responseBody)
                if (!jsonResponse.has("choices")) {
                    return@withContext Result.failure(Exception("Resposta inválida da API da Groq: $responseBody"))
                }

                val content = jsonResponse
                    .getJSONArray("choices")
                    .getJSONObject(0)
                    .getJSONObject("message")
                    .getString("content")
                    .trim()

                // Remove code block markdown formatting if generated by the LLM
                var cleanedContent = content
                if (cleanedContent.startsWith("```")) {
                    cleanedContent = cleanedContent.substringAfter("```json").substringAfter("```").substringBeforeLast("```").trim()
                }

                val json = JSONObject(cleanedContent)
                val title = json.getString("title")
                val shotsArray = json.getJSONArray("shots")
                val shots = (0 until shotsArray.length()).map { i ->
                    val s = shotsArray.getJSONObject(i)
                    GeneratedShot(
                        index = s.getInt("index"),
                        zone = s.getInt("zone"),
                        spinName = s.getString("spinName"),
                        velocity = s.getInt("velocity"),
                        freq = s.getString("freq"),
                        racketSide = s.optString("racketSide", "Forehand")
                    )
                }
                Result.success(GeneratedRoutine(title, shots))
            } catch (e: Exception) {
                Result.failure(e)
            }
        }

    suspend fun analyzeSession(
        routineTitle: String,
        durationMinutes: Int,
        reps: Int,
        accuracy: Int,
        racketSide: String,
        notes: String
    ): Result<String> = withContext(Dispatchers.IO) {
        try {
            val sessionPrompt = """
                Analisa esta sessão de treino de ténis de mesa e dá feedback construtivo em português de Portugal (máximo 4 parágrafos curtos):
                
                Rotina: $routineTitle
                Duração: $durationMinutes minutos
                Repetições: $reps
                Precisão sentida: $accuracy%
                Lado da raquete dominante: $racketSide
                Notas do jogador: ${notes.ifBlank { "Nenhuma" }}
                
                Foca-te em: o que correu bem, o que melhorar, sugestão para o próximo treino.
            """.trimIndent()

            val messages = JSONArray().apply {
                put(JSONObject().put("role", "user").put("content", sessionPrompt))
            }
            val body = JSONObject()
                .put("model", MODEL)
                .put("messages", messages)
                .put("temperature", 0.6)
                .put("max_tokens", 512)
                .toString()
                .toRequestBody("application/json".toMediaType())

                val request = Request.Builder()
                    .url(BASE_URL)
                    .addHeader("Authorization", "Bearer $API_KEY")
                    .addHeader("Content-Type", "application/json")
                    .post(body)
                    .build()

                val response = client.newCall(request).execute()
                val responseBody = response.body?.string() ?: return@withContext Result.failure(Exception("Vazio"))
                
                if (!response.isSuccessful) {
                    return@withContext Result.failure(Exception("Erro API (${response.code}): $responseBody"))
                }

                val jsonResponse = JSONObject(responseBody)
                if (!jsonResponse.has("choices")) {
                    return@withContext Result.failure(Exception("Campo 'choices' em falta na resposta: $responseBody"))
                }

                val content = jsonResponse
                    .getJSONArray("choices")
                    .getJSONObject(0)
                    .getJSONObject("message")
                    .getString("content")
                Result.success(content.trim())
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
